-- dec_role
ALTER ROLE DEC_ROLE RENAME TO DECEMBER_ROLE
-- december_wh
CREATE  WAREHOUSE DECEMBER_WH WITH WAREHOUSE_TYPE = STANDARD
WAREHOUSE_SIZE = XLARGE
MAX_CLUSTER_COUNT = 10
MIN_CLUSTER_COUNT = 1
SCALING_POLICY = STANDARD
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = FALSE
RESOURCE_MONITOR = NULL
COMMENT = 'VALIDATE'
ENABLE_QUERY_ACCELERATION = FALSE
QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8 MAX_CONCURRENCY_LEVEL = 1
STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60
STATEMENT_TIMEOUT_IN_SECONDS = 60;
