CREATE OR REPLACE  SEQUENCE demo_127.demo.seq_nm1 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';
CREATE OR REPLACE  SEQUENCE demo_127.demo.seq_nm2 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';
CREATE OR REPLACE  SEQUENCE demo_127.demo.seq_nm3 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';
CREATE OR REPLACE  SEQUENCE demo_127.demo.seq_nm4 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';
CREATE OR REPLACE  SEQUENCE demo_127.demo.seq_nm5 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';
CREATE  SEQUENCE demo_127.demo.seq_nm6 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';
CREATE  SEQUENCE demo_127.demo.seq_nm7 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';
CREATE  SEQUENCE demo_127.demo.seq_nm8 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';
CREATE  SEQUENCE demo_127.demo.seq_nm9 WITH START WITH = 1 INCREMENT BY = 1 COMMENT = '';