CREATE   DATABASE TEST_DB2 DATA_RETENTION_TIME_IN_DAYS = 5 MAX_DATA_EXTENSION_TIME_IN_DAYS = 2 COMMENT = 'Test DB2';
CREATE OR REPLACE  DATABASE TEST_DB3   COMMENT = 'Test DB3';
CREATE  TRANSIENT DATABASE TEST_DB4   COMMENT = 'Test DB4';